baseURL = "https://smartcitydays2023.netlify.app/"
languageCode = "fr-ch"
title = "Smart City Days 2023"


[params]
footer = """Cette page a été développée ce matin même comme exemple pratique et rapide. Les sources sont disponibles sur [GitHub](https://github.com/nfriedli/smart-city-days-2023). Le site est déployé automatiquement chez Netlify."""